"""rename department

Revision ID: 231210ace9eb
Revises: 2edc48eb0227
Create Date: 2024-10-02 15:03:35.608084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231210ace9eb'
down_revision = '2edc48eb0227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
