"""rename address

Revision ID: 88202f2f77d9
Revises: 231210ace9eb
Create Date: 2024-10-02 15:10:01.675313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88202f2f77d9'
down_revision = '231210ace9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
